name: hotel_book
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.16.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  image_stack: ^2.1.1
  get: ^4.1.4
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  flutter_spinkit:
  bottom_picker:
  intl:
  dropdown_search:

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets: [images/, images/icons/]
